# Generated by Django 2.2 on 2019-05-13 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillQuestBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Блок вопросов',
                'verbose_name_plural': 'Блоки вопросов',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkillTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123, verbose_name='Название')),
                ('count_of_quest', models.IntegerField(default=0, verbose_name='Количество вопросов в тесте')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkillTestDelegation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Назначение теста',
                'verbose_name_plural': 'Назначения тестов',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkillTestQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Текст вопроса')),
                ('is_few_right_answers', models.BooleanField(default=False, verbose_name='Несколько вариантов ответа?')),
                ('code', models.TextField(blank=True, null=True, verbose_name='Кусок кода')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkillTestQuestBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_questions', models.PositiveSmallIntegerField(verbose_name='Количество вопросов из блока')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='block', to='skilltests.SkillQuestBlock', verbose_name='Блок с вопросами, подготовленными специально для теста')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test', to='skilltests.SkillTest', verbose_name='Тест')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkillTestDelegationResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FloatField(blank=True, null=True, verbose_name='Результат')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Время начала прохождения')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время конца прохождения')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to=settings.AUTH_USER_MODEL, verbose_name='Человек, которому назначили тест')),
                ('skill_test_delegation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='skilltests.SkillTestDelegation', verbose_name='Назначение')),
            ],
        ),
        migrations.AddField(
            model_name='skilltestdelegation',
            name='profiles',
            field=models.ManyToManyField(related_name='skilltests_delegations', through='skilltests.SkillTestDelegationResult', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники'),
        ),
        migrations.AddField(
            model_name='skilltestdelegation',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegations', to='skilltests.SkillTest', verbose_name='Тест'),
        ),
        migrations.CreateModel(
            name='SkillTestAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Текст ответа')),
                ('code', models.TextField(blank=True, null=True, verbose_name='Кусок кода')),
                ('right', models.BooleanField(default=False, verbose_name='Правильный?')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='skilltests.SkillTestQuestion', verbose_name='На вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='skilltest',
            name='blocks',
            field=models.ManyToManyField(related_name='tests', through='skilltests.SkillTestQuestBlock', to='skilltests.SkillQuestBlock', verbose_name='Блоки с вопросами'),
        ),
        migrations.AddField(
            model_name='skilltest',
            name='questions',
            field=models.ManyToManyField(related_name='tests', to='skilltests.SkillTestQuestion', verbose_name='Все вопросы теста'),
        ),
        migrations.AddField(
            model_name='skillquestblock',
            name='questions',
            field=models.ManyToManyField(related_name='blocks', to='skilltests.SkillTestQuestion', verbose_name='Вопросы в блоке'),
        ),
    ]
