# Generated by Django 2.2 on 2019-05-13 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skilltests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltestdelegationresult',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_results', to=settings.AUTH_USER_MODEL, verbose_name='Человек, которому назначили тест'),
        ),
    ]
