# Generated by Django 2.2 on 2019-05-13 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123, verbose_name='Название')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='polls', to=settings.AUTH_USER_MODEL, verbose_name='Для сотрудника')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PollQuestBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Блок вопросов',
                'verbose_name_plural': 'Блоки вопросов',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PollQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Текст вопроса')),
                ('with_answer_option', models.BooleanField(default=False, verbose_name='С вариантами ответа')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PollTestQuestBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocks', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blocks', to='test360.PollQuestBlock', verbose_name='Блоки с вопросами')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test', to='test360.Poll', verbose_name='Тест')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pollquestblock',
            name='questions',
            field=models.ManyToManyField(related_name='blocks', to='test360.PollQuestion', verbose_name='Вопросы в блоке'),
        ),
        migrations.CreateModel(
            name='PollDelegation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='poll_delegations', to='test360.Poll', verbose_name='Опрос')),
                ('profiles', models.ManyToManyField(related_name='test360_delegations', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники')),
            ],
            options={
                'verbose_name': 'Назначение теста',
                'verbose_name_plural': 'Назначения тестов',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PollAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Текст ответа')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник, давший ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='test360.PollQuestion', verbose_name='Ответ на вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='poll',
            name='questions',
            field=models.ManyToManyField(related_name='polls', to='test360.PollQuestion', verbose_name='Вопросы в опросе'),
        ),
    ]
